"""
VAJRA - Markdown Recon Summary Report Generator
Generates a clean markdown summary of scan results.
Usage: python3 recon_summary.py <domain>
"""

import os
import sys
import datetime

def read_file(path):
    try:
        with open(path) as f:
            return [l.strip() for l in f if l.strip()]
    except:
        return []

def generate_summary(domain):
    base = f"output/{domain}"
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    subdomains = read_file(f"{base}/final_subdomains.txt")
    live_hosts = read_file(f"{base}/live_subdomains.txt")
    endpoints  = read_file(f"{base}/all_endpoints.txt")
    ports      = read_file(f"{base}/open_ports.txt")
    techs      = read_file(f"{base}/technologies.txt")

    def section(title, items, limit=20):
        if not items:
            return f"### {title}\n> No data found.\n\n"
        out = f"### {title} ({len(items)} total)\n"
        for item in items[:limit]:
            out += f"- `{item}`\n"
        if len(items) > limit:
            out += f"\n> ... and {len(items)-limit} more (see output file)\n"
        return out + "\n"

    md = f"""# 🔱 VAJRA Recon Summary Report

| Field | Value |
|-------|-------|
| 🎯 Target | `{domain}` |
| 📅 Date | {now} |
| 🔍 Subdomains | {len(subdomains)} |
| 🌐 Live Hosts | {len(live_hosts)} |
| 🗺️ Endpoints | {len(endpoints)} |
| 🔌 Open Ports | {len(ports)} |
| 🧠 Technologies | {len(techs)} |

---

{section("🔍 Subdomains Found", subdomains)}
{section("🌐 Live Hosts", live_hosts)}
{section("🔌 Open Ports", ports)}
{section("🧠 Technologies Detected", techs)}
{section("🗺️ Sample Endpoints", endpoints, limit=30)}

---

> ⚡ Generated by [VAJRA](https://github.com/gauravjethva-lab/vajra-web-enumeration)
> ⚠️ For authorized security testing only
"""

    out_path = f"{base}/recon_summary.md"
    os.makedirs(base, exist_ok=True)
    with open(out_path, "w") as f:
        f.write(md)

    print(f"\n✅ Markdown summary saved: {out_path}")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 recon_summary.py <domain>")
        sys.exit(1)
    generate_summary(sys.argv[1])
