"""
VAJRA - Markdown Recon Summary Generator
Usage: python3 recon_summary.py <domain>
Auto-called by main.py after scan completes.
"""

import os, sys, datetime


def read_file(path, limit=None):
    try:
        with open(path) as f:
            lines = [l.strip() for l in f if l.strip()]
        return lines[:limit] if limit else lines
    except:
        return []


def generate_summary(domain):
    base = f"output/{domain}"
    now  = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    subdomains = read_file(f"{base}/final_subdomains.txt")
    live_hosts = read_file(f"{base}/live_subdomains.txt")
    endpoints  = read_file(f"{base}/all_endpoints.txt")
    ports      = read_file(f"{base}/open_ports.txt")
    techs      = read_file(f"{base}/technologies.txt")
    dns        = read_file(f"{base}/dns_records.txt")
    whois_data = read_file(f"{base}/whois.txt")

    def section(title, items, limit=30):
        if not items:
            return f"### {title}\n> No data found.\n\n"
        out = f"### {title} ({len(items)} total)\n\n"
        for item in items[:limit]:
            out += f"- `{item}`\n"
        if len(items) > limit:
            out += f"\n> ... and {len(items) - limit} more — see output file.\n"
        return out + "\n"

    md = f"""# VAJRA Recon Summary

| Field | Value |
|-------|-------|
| Target | `{domain}` |
| Date | {now} |
| Subdomains | {len(subdomains)} |
| Live Hosts | {len(live_hosts)} |
| Endpoints | {len(endpoints)} |
| Open Ports | {len(ports)} |
| Technologies | {len(techs)} |
| DNS Records | {len(dns)} |

---

{section("WHOIS Info", whois_data)}
{section("DNS Records", dns)}
{section("Subdomains Found", subdomains)}
{section("Live Hosts", live_hosts)}
{section("Open Ports", ports)}
{section("Technologies Detected", techs)}
{section("Sample Endpoints", endpoints, limit=30)}

---

> Generated by [VAJRA](https://github.com/gauravjethva-lab/vajra-web-enumeration)
> For authorized security testing only.
"""

    out_path = f"{base}/recon_summary.md"
    with open(out_path, "w") as f:
        f.write(md)

    print(f"\n[+] Markdown summary saved: {out_path}")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 recon_summary.py <domain>")
        sys.exit(1)
    generate_summary(sys.argv[1])
