"""
VAJRA - HTML Scan Report Generator
Generates a professional HTML report from scan output files.
Usage: python3 report_generator.py <domain>
"""

import os
import sys
import datetime

def read_file(path):
    try:
        with open(path, "r") as f:
            lines = [l.strip() for l in f.readlines() if l.strip()]
        return lines
    except:
        return []

def generate_report(domain):
    base = f"output/{domain}"
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    subdomains  = read_file(f"{base}/final_subdomains.txt")
    live_hosts  = read_file(f"{base}/live_subdomains.txt")
    endpoints   = read_file(f"{base}/all_endpoints.txt")
    ports       = read_file(f"{base}/open_ports.txt")
    techs       = read_file(f"{base}/technologies.txt")

    def make_list(items, color="#00ff88"):
        if not items:
            return "<p style='color:#666'>No data found.</p>"
        return "".join(f"<div class='item'>{i}</div>" for i in items)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>VAJRA Report — {domain}</title>
  <style>
    * {{ margin:0; padding:0; box-sizing:border-box; }}
    body {{ background:#0d1117; color:#c9d1d9; font-family:'Courier New',monospace; padding:30px; }}
    .header {{ text-align:center; padding:40px 0; border-bottom:2px solid #30363d; margin-bottom:30px; }}
    .header pre {{ color:#f0883e; font-size:12px; line-height:1.2; }}
    h1 {{ color:#f0883e; font-size:28px; margin-top:15px; }}
    .meta {{ color:#8b949e; margin-top:8px; font-size:14px; }}
    .stats {{ display:flex; gap:20px; flex-wrap:wrap; margin-bottom:30px; }}
    .stat-card {{ background:#161b22; border:1px solid #30363d; border-radius:8px;
                  padding:20px 30px; flex:1; min-width:150px; text-align:center; }}
    .stat-card .num {{ font-size:36px; font-weight:bold; color:#f0883e; }}
    .stat-card .label {{ color:#8b949e; font-size:13px; margin-top:5px; }}
    .section {{ background:#161b22; border:1px solid #30363d; border-radius:8px;
                padding:25px; margin-bottom:25px; }}
    .section h2 {{ color:#f0883e; font-size:18px; margin-bottom:15px;
                   padding-bottom:10px; border-bottom:1px solid #30363d; }}
    .item {{ padding:6px 10px; border-left:3px solid #f0883e; margin:5px 0;
             background:#0d1117; border-radius:0 4px 4px 0; font-size:13px;
             color:#00ff88; word-break:break-all; }}
    .footer {{ text-align:center; color:#8b949e; font-size:12px;
               margin-top:30px; padding-top:20px; border-top:1px solid #30363d; }}
    .badge {{ display:inline-block; background:#f0883e; color:#000;
              padding:2px 10px; border-radius:20px; font-size:11px; font-weight:bold; }}
  </style>
</head>
<body>
  <div class="header">
    <pre>
██╗   ██╗ █████╗      ██╗██████╗  █████╗
██║   ██║██╔══██╗     ██║██╔══██╗██╔══██╗
██║   ██║███████║     ██║██████╔╝███████║
╚██╗ ██╔╝██╔══██║██   ██║██╔══██╗██╔══██║
 ╚████╔╝ ██║  ██║╚█████╔╝██████╔╝██║  ██║
  ╚═══╝  ╚═╝  ╚═╝ ╚════╝ ╚═════╝ ╚═╝  ╚═╝
    </pre>
    <h1>⚡ VAJRA Scan Report</h1>
    <div class="meta">
      🎯 Target: <strong style="color:#f0883e">{domain}</strong> &nbsp;|&nbsp;
      🕐 Generated: {now} &nbsp;|&nbsp;
      <span class="badge">v1.0.0</span>
    </div>
  </div>

  <div class="stats">
    <div class="stat-card"><div class="num">{len(subdomains)}</div><div class="label">🔍 Subdomains</div></div>
    <div class="stat-card"><div class="num">{len(live_hosts)}</div><div class="label">🌐 Live Hosts</div></div>
    <div class="stat-card"><div class="num">{len(endpoints)}</div><div class="label">🗺️ Endpoints</div></div>
    <div class="stat-card"><div class="num">{len(ports)}</div><div class="label">🔌 Open Ports</div></div>
    <div class="stat-card"><div class="num">{len(techs)}</div><div class="label">🧠 Technologies</div></div>
  </div>

  <div class="section">
    <h2>🔍 Subdomains ({len(subdomains)} found)</h2>
    {make_list(subdomains)}
  </div>

  <div class="section">
    <h2>🌐 Live Hosts ({len(live_hosts)} found)</h2>
    {make_list(live_hosts)}
  </div>

  <div class="section">
    <h2>🗺️ Endpoints ({len(endpoints)} found)</h2>
    {make_list(endpoints[:100])}
    {"<p style='color:#8b949e;margin-top:10px'>... and " + str(len(endpoints)-100) + " more (see all_endpoints.txt)</p>" if len(endpoints) > 100 else ""}
  </div>

  <div class="section">
    <h2>🔌 Open Ports ({len(ports)} found)</h2>
    {make_list(ports)}
  </div>

  <div class="section">
    <h2>🧠 Technologies Detected ({len(techs)} found)</h2>
    {make_list(techs)}
  </div>

  <div class="footer">
    <p>⚡ Generated by <strong>VAJRA Web Enumeration Framework</strong></p>
    <p style="margin-top:5px">⚠️ For authorized security testing only</p>
  </div>
</body>
</html>"""

    out_path = f"{base}/vajra_report.html"
    os.makedirs(base, exist_ok=True)
    with open(out_path, "w") as f:
        f.write(html)

    print(f"\n✅ HTML Report saved: {out_path}")
    print(f"   Open in browser: firefox {out_path}")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 report_generator.py <domain>")
        print("Example: python3 report_generator.py example.com")
        sys.exit(1)
    generate_report(sys.argv[1])
